/**
 * Windows-safe native-module rebuild helper
 *
 * Fixes two node-pty build issues on Windows before running electron-rebuild:
 *
 * 1. winpty.gyp batch-file actions
 *    winpty.gyp uses <!()> to call GetCommitHash.bat and UpdateGenVersion.bat
 *    via `cmd /c "cd shared && <bat>"`. This pattern fails when node-gyp is
 *    spawned from a Git Bash environment. Fix: patch winpty.gyp to replace
 *    the dynamic calls with their known static outputs so no batch file runs.
 *
 * 2. Spectre-mitigated libraries (MSB8040)  [kept as defence-in-depth]
 *    binding.gyp sets SpectreMitigation=Spectre. If the VS "Spectre-mitigated
 *    C++ libs" component is missing the build fails. Fix: patch binding.gyp to
 *    set SpectreMitigation to an empty string, which satisfies the toolset
 *    without requiring the extra VS component.
 *
 * On non-Windows platforms both patches are skipped.
 *
 * Usage (called automatically via "rebuild:native"):
 *   node scripts/rebuild-native.js
 */
const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

const ROOT = path.join(__dirname, "..");
const NODE_PTY = path.join(ROOT, "node_modules", "node-pty");

// ──────────────────────────────────────────────
//  Patch 1 – winpty.gyp batch-file actions
// ──────────────────────────────────────────────
//
// Original:
//   'WINPTY_COMMIT_HASH%': '<!(cmd /c "cd shared && GetCommitHash.bat")',
//   '<!(cmd /c "cd shared && UpdateGenVersion.bat <(WINPTY_COMMIT_HASH)")',
//
// The <!()> call captures stdout from the bat file:
//   GetCommitHash.bat  → echoes the git commit hash, or "none"
//   UpdateGenVersion.bat → creates gen/GenVersion.h and then echoes "gen"
//                          (the include dir relative to src/)
//
// We pre-create GenVersion.h with stable content and hard-code the outputs.

const WINPTY_GYP = path.join(NODE_PTY, "deps", "winpty", "src", "winpty.gyp");
const GEN_DIR    = path.join(NODE_PTY, "deps", "winpty", "src", "gen");
const GEN_H      = path.join(GEN_DIR, "GenVersion.h");

const GEN_H_CONTENT = `// AUTO-GENERATED by scripts/rebuild-native.js
const char GenVersion_Version[] = "0.4.4-dev";
const char GenVersion_Commit[] = "none";
`;

function patchWinptyGyp() {
  if (!fs.existsSync(WINPTY_GYP)) {
    console.warn("⚠️  winpty.gyp not found – skipping batch-file patch");
    return;
  }

  // Ensure gen/GenVersion.h exists so the compiler finds it
  if (!fs.existsSync(GEN_DIR)) fs.mkdirSync(GEN_DIR, { recursive: true });
  if (!fs.existsSync(GEN_H)) {
    fs.writeFileSync(GEN_H, GEN_H_CONTENT);
    console.log("  ✏️  Created gen/GenVersion.h");
  }

  let src = fs.readFileSync(WINPTY_GYP, "utf-8");

  // Check if already patched (look for hardcoded 'none' replacing the bat call)
  if (!src.includes("GetCommitHash.bat") && !src.includes("UpdateGenVersion.bat")) {
    console.log("ℹ️  winpty.gyp already patched");
    return;
  }

  // Replace the GetCommitHash.bat call – output is always the commit hash or "none"
  src = src.replace(
    /'\s*<!\(\s*cmd\s+\/c\s+"cd shared && GetCommitHash\.bat"\s*\)\s*'/,
    "'none'"
  );

  // Replace the UpdateGenVersion.bat call – output is the include dir: "gen"
  src = src.replace(
    /'\s*<!\(\s*cmd\s+\/c\s+"cd shared && UpdateGenVersion\.bat\s*<\(WINPTY_COMMIT_HASH\)\s*"\s*\)\s*'/,
    "'gen'"
  );

  // Also clear SpectreMitigation inside winpty.gyp itself
  src = src.replace(/'SpectreMitigation':\s*'Spectre'/g, "'SpectreMitigation': ''");

  fs.writeFileSync(WINPTY_GYP, src);
  console.log("  ✏️  Patched winpty.gyp (removed batch-file <!()> calls + SpectreMitigation)");
}

// ──────────────────────────────────────────────
//  Patch 2 – Spectre mitigation (defence-in-depth)
// ──────────────────────────────────────────────

const BINDING_GYP = path.join(NODE_PTY, "binding.gyp");

function patchBindingGyp() {
  if (!fs.existsSync(BINDING_GYP)) {
    console.warn("⚠️  binding.gyp not found – skipping Spectre patch");
    return;
  }

  let src = fs.readFileSync(BINDING_GYP, "utf-8");

  if (!src.includes("'SpectreMitigation': 'Spectre'")) {
    console.log("ℹ️  binding.gyp Spectre entry already absent or patched");
    return;
  }

  src = src.replace("'SpectreMitigation': 'Spectre'", "'SpectreMitigation': ''");
  fs.writeFileSync(BINDING_GYP, src);
  console.log("  ✏️  Patched binding.gyp (SpectreMitigation: Spectre → empty)");
}

// ──────────────────────────────────────────────
//  Run electron-rebuild
// ──────────────────────────────────────────────

function runElectronRebuild() {
  const bin = path.join(
    ROOT, "node_modules", ".bin",
    process.platform === "win32" ? "electron-rebuild.cmd" : "electron-rebuild"
  );
  const cmd = fs.existsSync(bin) ? bin : "electron-rebuild";

  console.log(`\n▶  Running: ${path.basename(cmd)}\n`);
  const result = spawnSync(cmd, [], {
    stdio: "inherit",
    shell: true,
    cwd: ROOT,
    env: {
      ...process.env,
      // Suppress DEP0147/DEP0187 emitted by @electron/node-gyp's vendored tar
      // and find-visualstudio.js — these are third-party issues we cannot patch.
      NODE_NO_WARNINGS: "1",
    },
  });

  if (result.status !== 0) {
    console.error("\n❌ electron-rebuild failed");
    process.exit(result.status ?? 1);
  }

  console.log("\n✅ electron-rebuild succeeded");
}

// ──────────────────────────────────────────────
//  Main
// ──────────────────────────────────────────────

function main() {
  if (process.platform === "win32") {
    console.log("🪟  Windows – applying node-pty build patches …");
    patchWinptyGyp();
    patchBindingGyp();
    console.log();
  }

  runElectronRebuild();
}

main();
